### ISSUE TITLE
Trouble running NOAA OISST and World Ocean Atlas tutorial recipes

### ISSUE THREAD

**Issue by nbarlowATI** [pangeo-forge/pangeo-forge#107]
Hi, apologies for this long post, particularly as it's probably something very simple I'm doing wrong, but I'm having trouble running any of the pangeo-forge tutorial recipes I've found for converting netcdf to zarr.

I'm using python 3.7.10, the latest (as of April 20th) `master` branch of pangeo-forge, and `xarray==0.17.0`, `zarr==2.7.0`.

For the [OISST recipe](https://pangeo-forge.readthedocs.io/en/latest/tutorials/netcdf_zarr_sequential.html), 
* I don't think this one is important, but just for completeness, the output of `recipe.inputs_for_chunk(all_chunks[-1])` is not the same as in the tutorial - rather than the full input URLs, I get a tuple of (I guess) IDs of the inputs.
* Also don't think this one is important, but again, for completeness, I don't get the `UninitializedTargetError` when I try `recipe.open_chunk(all_chunks[0])` (because `open_chunk` returns a GeneratorContextManager, so I guess it's not trying to open the chunk since it's not in a `with` context). 
  - Same for Step 6, I had to do 
   `
with recipe.open_chunk(all_chunks[0]) as ds_chunk:
        print(ds_chunk)
  `  to see the expected output.
* Then, the first real problem comes when I try to prepare the target:
```
>>> recipe.prepare_target()
Traceback (most recent call last):
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/pangeo_forge/recipe.py", line 266, in _prepare_target
    ds = self.open_target()
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/pangeo_forge/recipe.py", line 476, in open_target
    return xr.open_zarr(target_mapper)
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/xarray/backends/zarr.py", line 679, in open_zarr
    use_cftime=use_cftime,
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/xarray/backends/api.py", line 554, in open_dataset
    store = opener(filename_or_obj, **extra_kwargs, **backend_kwargs)
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/xarray/backends/zarr.py", line 324, in open_group
    zarr_group = zarr.open_group(store, **open_kwargs)
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/zarr/hierarchy.py", line 1166, in open_group
    raise GroupNotFoundError(path)
zarr.errors.GroupNotFoundError: group not found at path ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/pangeo_forge/recipe.py", line 313, in _prepare_target
    ds.to_zarr(target_mapper, mode="a", compute=False, safe_chunks=False)
TypeError: to_zarr() got an unexpected keyword argument 'safe_chunks'
```
I don't know what to make of the "GroupNotFoundError", but I did look at the xarray `Dataset.to_zarr` method and didn't see a "safe_chunks" argument.  Is this a new/upcoming feature?

Next, I had a go at the [NOAA World Ocean Atlas recipe]( https://pangeo-forge.readthedocs.io/en/latest/tutorials/multi_variable_recipe.html).
* If I go all the way through, and do `flow.run()`, the first 23 tasks (presumably caching the inputs?) succeed, but then I get the same error as above, with "GroupNotFoundError", and the "safe_chunks" unexpected keyword argument.
* If I try to do the first chunk by hand I get: 
```
>>> all_chunks = list(recipe.iter_chunks())
>>> recipe.prepare_target()
>>> recipe.store_chunk(all_chunks[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/pangeo_forge/recipe.py", line 359, in _store_chunk
    zarr_array = zgroup[vname]
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/zarr/hierarchy.py", line 349, in __getitem__
    raise KeyError(item)
KeyError: 'time'
>>> recipe.prepare_target()
>>> recipe.store_chunk(all_chunks[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/pangeo_forge/recipe.py", line 359, in _store_chunk
    zarr_array = zgroup[vname]
  File "/Users/nbarlow/anaconda3/envs/pangeo-transfer-env/lib/python3.7/site-packages/zarr/hierarchy.py", line 349, in __getitem__
    raise KeyError(item)
KeyError: 'time'
```
which is a bit strange to me, as if I do
```
>>> with recipe.open_chunk(all_chunks[0]) as ds_chunk:
>>>      print(ds_chunk.variables)
```
I do see "time" listed.

Apologies again if all this is just me missing something obvious, but any help in debugging this would be very welcome (and I'd be happy to contribute (at the very least a recipe) to pangeo-forge once I gain some more understanding!)

**Comment by naomi-henderson** [comment]
hi @nbarlowATI , I had many of the same issues when I tried the OISST recipe (see, for example, my comment on [issue#51](https://github.com/pangeo-forge/pangeo-forge/issues/51#issuecomment-814483499) and Ryan's helpful reply [here](https://github.com/pangeo-forge/pangeo-forge/issues/51#issuecomment-814857503).  
To get past the `safe_chunks` problem, I resorted to editing `recipe.py` as explained [here](https://github.com/pangeo-forge/pangeo-forge/issues/51#issuecomment-814483499)
I was going to try updating the OISST recipe/tutorial, but only got as far as introducing a CMIP6 tutorial instead. Sorry about that, I know how frustrating this is!  It is fantastic that the code base is advancing so quickly, but it makes it difficult to keep the tutorials current.

**Comment by nbarlowATI** [comment]
Many thanks for the super fast reply @naomi-henderson !
As you suggest, just commenting out the "safe_chunks" argument in `recipe.py` does fix this! :)
I'll try now with the mamba environment instead.
I'm happy to look into updating the tutorials (though if that xarray PR is going to be merged soon it might be better to wait for that rather than write instructions on installing that branch).

Thanks again! :)
